apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0 # Cập nhật phiên bản nếu cần
    chart: ingress-nginx
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

